#+LATEX_HEADER: \usepackage[margin=0.6in]{geometry}
* Running the Program
- This assumes you have some version of ~python3~ and ~pip~ installed on your computer. If you don't, view https://wiki.python.org/moin/BeginnersGuide/Download to download python and https://pip.pypa.io/en/stable/installing/ to install pip
- Run ~pip install -r requirements.txt~ in your terminal, to install the necessary packages
- To open up the settings, navigate to the product folder and run ~python3 webform.py~
- To run the main classification program (only do so after you have configured the program to your liking), run the command ~python3 gdrive_tools.py~. The program will run in the background until you kill it or restart your computer.
* Functionality
The program runs its classifier periodically. Once the program is activated, it will run automatically every 10 or so minutes (depending on how you configured it). The program examines documents within a specific folder, and tags/classifies them as best as it can
** Classification
The program tags documents with the following metadata:
#+BEGIN_SRC json
{
"type": ("source", "note", "position", "resolution", "unclassified"),
"agenda": "string",
"committee": "string",
"country": "string",
"filetype": ("html", "pdf", "docx", "gdoc", "md", "etc."),
}
#+END_SRC
The metadata is stored in the file's description, and used for things such as searches, sorting, etc. The metadata is added based on heuristics, so it's not guaranteed to be perfect.
** Links
The program also reformats `naked' links found in documents with a string of the format ~<title>|<source> [<url>]~
* Configuration
** General
*** Delay
The app scans Google Drive at regular intervals. Increasing this value should make the app consume less memory/CPU, and decreasing it lets it update/scan documents more quickly.
*** Auto-format
The auto-format feature isn't currently supported, so this option does nothing. Documentation will be updated when that changes.
*** Folder Path
The app scans all files within a specified folder. Enter `/' (forward slash) here to make it scan the top-level drive, and enter ~/<foldername>~ to have it scan within a particular folder. You can specify complex paths as follows: ~/folder/subfolder/subsubfolder~
*** Authorisation
The program uses OAuth to access Google Drive without knowing the user's password. To remove the app's access to your Drive files, simply click the /de-authorise application/ button and close the tab after a few seconds. If you wish to re-enable this access, open up the configuration UI again, click /re-authorise application/, and sign in with your Google account when prompted to do so.
** Custom Rules
You can define custom classification rules, which classify documents as position papers, resolutions, etc. based on either
1. Whether the title contains a certain phrase
2. Whether the document text contains a certain phrase
These custom rules override the built-in rules the program uses, so if you have a personal convention for naming files the program can leverage that.
